### ISSUE TITLE
Multiple subpages with posts - no metadata shown

### ISSUE THREAD

**Issue by s3gm3nt4ti0nf4ult** [comfusion/after-dark#118]
Hi there,

As I want to host my blog in 2 languages I need 2 subpages. Posts are in language1 and language2. Unfortunately when I create these two directories in `content` directory and add them to the menu like that:

```toml
[[menu.main]]
  name = "#post-lnag1"
  weight = 2
  identifier = "postlang1"
  url = "/postlang1/"

[[menu.main]]
  name = "#post-lang2"
  weight = 3
  identifier = "postlang2"
  url = "/enlang2/"
```

No metadata like publishdate, tags and length is shown/generated. I find it pretty useful to determine when I created last post and stuff like that.
I could create new "blog" with only one page and redirect one language-posts to it, but maybe there is a simpler sollution, to enable this feature and do not bother with next installation and configuration?
