### ISSUE TITLE
Change background color of highlight area (code)

### ISSUE THREAD

**Issue by h-2** [comfusion/after-dark#36]
Hey,

I really like the theme and have been tuning it to fit my requirements better and it works great. Except one thing: the code blocks have black background, too and I'd like to change that.

I am using syntax highlighting with
```toml
PygmentsCodeFences = true
pygmentsuseclasses = true
```
And have added 
```css
.highlight { background: #002b36;  }
.highlight .hll { background-color: #ffffcc }
.highlight .c { color: #586e75; font-style: italic } /* Comment */
.highlight .err { color: #dc322f } /* Error */
.highlight .g { color: #839496 } /* Generic */
.highlight .k { color: #859900 } /* Keyword */
.highlight .l { color: #839496 } /* Literal */
...
```
to my `layouts/partials/critical-custom.css`. The settings for the elements all work well, however, the background of the code area is still black. Am I missing something here? Or is this maybe overwritten somewhere else?

Thanks for your help!
