### ISSUE TITLE
post or article in subfolder and associated address/link

### ISSUE THREAD

**Issue by Polarhardboiled** [comfusion/after-dark#41]
Hi,
I am trying to use your easy, simple, fast and great theme for hugo but facing one issue.
I put each single post in a subfolder of a general news folder. Every think works fine but the address of a single post "post-1" is as follows:
`../news/post-1/post-1   ` where I would like to have only `../news/post-1` .
Any idea of how to fix it ?
Thank a lot

**Comment by jhabdas** [comment]
You have a content structure like this:

```
content
└── news
    ├── post-1
    │   └── post-1.md
    └── post-2
        └── post-2.md
```

And you want to control the URLs output so they do not use nested directories. Correct?

- If yes, you will want to specify the `permalink` [page variable](https://gohugo.io/templates/variables#taxonomy-terms-page-variables) for each item created. Because nested directories are dynamically named, [archetypes](https://gohugo.io/themes/creation#archetypes) will _not_ accommodate your needs. At least as they are built out in Hugo today.
- If no, please reopen this issue and help adjust my understanding of your needs.

For general Q&A, please head over to the [Hugo discussion forums](https://discuss.gohugo.io/). Issues here should be specific to After Dark, which this is not from what I can tell.

**Comment by jhabdas** [comment]
@Polarhardboiled Slight adjustment to guidance. I got my Jekyll mixed up with my Hugo. With Hugo you want to use the `url` page param and not `permalink`, e.g.

```toml
+++
title = "Privacy Policy"
description = "Your Privacy on Hack Cabin"
date = "2017-06-16T17:42:00+08:00"
publishdate = "2017-01-30T14:05:48+08:00"
url = "/privacy/"
noindex = true
+++
```
