### ISSUE TITLE
Ordered lists sized > 9 appear misaligned

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#59]
Wait until hack update before fixing to prevent duplication of work. Here's the hotfix for your `critical-custom.css` partials:

```css
.hack ol li:nth-child(n+10):after {
  left: -11px;
}
```

Updates: https://github.com/egoist/hack/pull/59
